const years = [
  {
    "OMI": 1225,
    "accessDenial": 13,
    "breach": 345,
    "capitalImprovement": 55,
    "condoConversion": 1,
    "count": 2484,
    "demolition": 54,
    "ellisAct": 6,
    "failureToSignRenewal": 2,
    "illegalUse": 20,
    "latePayments": 106,
    "nonPayment": 124,
    "nuisance": 267,
    "otherCause": 192,
    "roommateSameUnit": 104,
    "substantialRehab": 39,
    "unapprovedSubtenant": 78,
    "year": 1997,
  },
  {
    "OMI": 1538,
    "accessDenial": 12,
    "breach": 321,
    "capitalImprovement": 27,
    "condoConversion": 1,
    "count": 1849,
    "demolition": 61,
    "ellisAct": 95,
    "failureToSignRenewal": 2,
    "illegalUse": 17,
    "latePayments": 95,
    "nonPayment": 144,
    "nuisance": 249,
    "otherCause": 162,
    "roommateSameUnit": 81,
    "substantialRehab": 16,
    "unapprovedSubtenant": 99,
    "year": 1998
  },
  {
    "OMI": 872,
    "accessDenial": 11,
    "breach": 316,
    "capitalImprovement": 59,
    "condoConversion": 2,
    "count": 1832,
    "demolition": 50,
    "ellisAct": 423,
    "failureToSignRenewal": 3,
    "illegalUse": 27,
    "latePayments": 100,
    "nonPayment": 164,
    "nuisance": 256,
    "otherCause": 73,
    "roommateSameUnit": 144,
    "substantialRehab": 1,
    "unapprovedSubtenant": 191,
    "year": 1999
  },
  {
    "OMI": 1012,
    "accessDenial": 13,
    "breach": 382,
    "capitalImprovement": 87,
    "condoConversion": 4,
    "count": 2027,
    "demolition": 71,
    "ellisAct": 274,
    "failureToSignRenewal": 6,
    "illegalUse": 35,
    "latePayments": 95,
    "nonPayment": 117,
    "nuisance": 274,
    "otherCause": 108,
    "roommateSameUnit": 146,
    "substantialRehab": 4,
    "unapprovedSubtenant": 27,
    "year": 2000
  },
  {
    "OMI": 802,
    "accessDenial": 9,
    "breach": 387,
    "capitalImprovement": 49,
    "condoConversion": 7,
    "count": 1504,
    "demolition": 99,
    "ellisAct": 194,
    "failureToSignRenewal": 2,
    "illegalUse": 36,
    "latePayments": 66,
    "leadRemediation": 1,
    "nonPayment": 111,
    "nuisance": 267,
    "otherCause": 66,
    "roommateSameUnit": 119,
    "substantialRehab": 6,
    "unapprovedSubtenant": 22,
    "year": 2001
  },
  {
    "OMI" : 548,
    "accessDenial": 8,
    "breach": 253,
    "capitalImprovement": 64,
    "condoConversion": 4,
    "count": 276,
    "demolition": 75,
    "ellisAct": 176,
    "failureToSignRenewal": 1,
    "illegalUse": 21,
    "latePayments": 71,
    "nonPayment": 94,
    "nuisance": 255,
    "otherCause": 17,
    "roommateSameUnit": 84,
    "substantialRehab": 1,
    "unapprovedSubtenant": 9,
    "year": 2002
  },
  {
    "OMI": 357,
    "accessDenial": 7,
    "breach": 285,
    "capitalImprovement": 72,
    "condoConversion": 8,
    "count": 487,
    "demolition": 93,
    "ellisAct": 145,
    "failureToSignRenewal": 1,
    "illegalUse": 23,
    "latePayments": 56,
    "nonPayment": 122,
    "nuisance": 285,
    "otherCause": 38,
    "roommateSameUnit": 53,
    "substantialRehab": 2,
    "unapprovedSubtenant": 10,
    "year": 2003
  },
  {
    "OMI": 345,
    "accessDenial": 2,
    "breach": 212,
    "capitalImprovement": 48,
    "condoConversion": 8,
    "count": 1344,
    "demolition": 67,
    "ellisAct": 303,
    "illegalUse": 21,
    "latePayments": 54,
    "nonPayment": 85,
    "nuisance": 234,
    "otherCause": 34,
    "roommateSameUnit": 58,
    "unapprovedSubtenant": 16,
    "year": 2004
  },
  {
    "OMI": 267,
    "accessDenial": 7,
    "breach": 293,
    "capitalImprovement": 89,
    "count": 1531,
    "demolition": 61,
    "ellisAct": 298,
    "illegalUse": 32,
    "latePayments": 55,
    "nonPayment": 89,
    "nuisance": 336,
    "otherCause": 40,
    "roommateSameUnit": 45,
    "unapprovedSubtenant": 14,
    "year": 2005
  },
  {

    "OMI": 227,
    "accessDenial": 14,
    "breach": 280,
    "capitalImprovement": 78,
    "condoConversion": 3,
    "count": 1122,
    "demolition": 42,
    "ellisAct": 262,
    "illegalUse": 49,
    "latePayments": 67,
    "nonPayment": 99,
    "nuisance": 288,
    "otherCause": 51,
    "roommateSameUnit": 51,
    "substantialRehab": 5,
    "unapprovedSubtenant": 23,
    "year": 2006
  },
  {
    "OMI": 181,
    "accessDenial": 20,
    "breach": 377,
    "capitalImprovement": 56,
    "condoConversion": 3,
    "count": 1207,
    "demolition": 43,
    "ellisAct": 237,
    "failureToSignRenewal": 9,
    "illegalUse": 38,
    "latePayments": 80,
    "leadRemediation": 3,
    "nonPayment": 129,
    "nuisance": 323,
    "otherCause": 40,
    "roommateSameUnit": 23,
    "unapprovedSubtenant": 16,
    "year": 2007
  },
  {
    "OMI": 169,
    "accessDenial": 18,
    "breach": 378,
    "capitalImprovement": 28,
    "condoConversion": 2,
    "count": 827,
    "demolition": 38,
    "ellisAct": 194,
    "failureToSignRenewal": 2,
    "illegalUse": 45,
    "latePayments": 83,
    "nonPayment": 102,
    "nuisance": 324,
    "otherCause": 53,
    "roommateSameUnit": 27,
    "unapprovedSubtenant": 20,
    "year": 2008
  },
  {
    "OMI": 120,
    "accessDenial": 13,
    "breach": 411,
    "capitalImprovement": 24,
    "condoConversion": 2,
    "count": 556,
    "demolition": 33,
    "ellisAct": 48,
    "failureToSignRenewal": 6,
    "illegalUse": 36,
    "latePayments": 81,
    "leadRemediation": 3,
    "nonPayment": 111,
    "nuisance": 260,
    "otherCause": 59,
    "roommateSameUnit": 25,
    "unapprovedSubtenant": 20,
    "year": 2009
  },
  {
    "OMI": 127,
    "accessDenial": 29,
    "breach": 448,
    "capitalImprovement": 22,
    "condoConversion": 4,
    "count": 897,
    "demolition": 31,
    "development": 106,
    "ellisAct": 70,
    "failureToSignRenewal": 9,
    "illegalUse": 19,
    "latePayments": 52,
    "nonPayment": 84,
    "nuisance": 295,
    "otherCause": 72,
    "roommateSameUnit": 36,
    "unapprovedSubtenant": 13,
    "year": 2010
  },
  {
    "OMI": 124,
    "accessDenial": 26,
    "breach": 536,
    "capitalImprovement": 45,
    "condoConversion": 2,
    "count": 758,
    "demolition": 37,
    "ellisAct": 54,
    "failureToSignRenewal": 4,
    "illegalUse": 30,
    "latePayments": 46,
    "nonPayment": 90,
    "nuisance": 246,
    "otherCause": 59,
    "roommateSameUnit": 28,
    "substantialRehab": 1,
    "unapprovedSubtenant": 21,
    "year": 2011
  },
  {
    "OMI": 174,
    "accessDenial": 11,
    "breach": 445,
    "capitalImprovement": 28,
    "condoConversion": 11,
    "count": 1451,
    "demolition": 43,
    "development": 232,
    "ellisAct": 99,
    "failureToSignRenewal": 7,
    "illegalUse": 36,
    "latePayments": 59,
    "nonPayment": 80,
    "nuisance": 338,
    "otherCause": 66,
    "roommateSameUnit": 37,
    "unapprovedSubtenant": 18,
    "year": 2012
  },
  {
    "OMI": 275,
    "accessDenial": 15,
    "breach": 598,
    "capitalImprovement": 31,
    "condoConversion": 12,
    "count": 1711,
    "demolition": 129,
    "ellisAct": 231,
    "failureToSignRenewal": 11,
    "illegalUse": 45,
    "latePayments": 78,
    "nonPayment": 75,
    "nuisance": 359,
    "otherCause": 56,
    "roommateSameUnit": 41,
    "substantialRehab": 6,
    "unapprovedSubtenant": 19,
    "year": 2013
  },
  {
    "OMI": 318,
    "accessDenial": 13,
    "breach": 726,
    "capitalImprovement": 42,
    "condoConversion": 10,
    "count": 1895,
    "demolition": 48,
    "ellisAct": 102,
    "failureToSignRenewal": 3,
    "illegalUse": 93,
    "latePayments": 66,
    "nonPayment": 144,
    "nuisance": 400,
    "otherCause": 48,
    "roommateSameUnit": 58,
    "unapprovedSubtenant": 19,
    "year": 2014
  },
  {
    "OMI": 423,
    "accessDenial": 21,
    "breach": 655,
    "capitalImprovement": 46,
    "condoConversion": 18,
    "count": 1215,
    "demolition": 61,
    "development": 1,
    "ellisAct": 146,
    "failureToSignRenewal": 3,
    "illegalUse": 84,
    "latePayments": 93,
    "nonPayment": 119,
    "nuisance": 359,
    "otherCause": 51,
    "roommateSameUnit": 46,
    "unapprovedSubtenant": 26,
    "year": 2015
  },
  {
    "OMI": 398,
    "accessDenial": 7,
    "breach": 449,
    "capitalImprovement": 302,
    "condoConversion": 5,
    "count": 1475,
    "demolition": 15,
    "development": 1,
    "ellisAct": 147,
    "failureToSignRenewal": 4,
    "illegalUse": 95,
    "latePayments": 126,
    "nonPayment": 128,
    "nuisance": 375,
    "otherCause": 30,
    "roommateSameUnit": 76,
    "unapprovedSubtenant": 21,
    "year": 2016
  },
  {
    "OMI": 314,
    "accessDenial": 29,
    "breach": 402,
    "capitalImprovement": 66,
    "condoConversion": 5,
    "count": 1125,
    "demolition": 3,
    "ellisAct": 181,
    "failureToSignRenewal": 8,
    "illegalUse": 57,
    "latePayments": 60,
    "nonPayment": 84,
    "nuisance": 313,
    "otherCause": 24,
    "roommateSameUnit": 26,
    "unapprovedSubtenant": 27,
    "year": 2017
  },
  {
    "OMI": 31,
    "accessDenial": 2,
    "breach": 61,
    "capitalImprovement": 57,
    "condoConversion": 1,
    "count": 50,
    "ellisAct": 36,
    "failureToSignRenewal": 1,
    "illegalUse": 4,
    "latePayments": 9,
    "nonPayment": 15,
    "nuisance": 58,
    "otherCause": 1,
    "roommateSameUnit": 2,
    "unapprovedSubtenant": 6,
    "year": 2018
  }
]
